# Generated by Django 5.1.3 on 2024-11-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_numnber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
