# Generated by Django 5.1.3 on 2024-11-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_onetimecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numnber',
            new_name='phone_number',
        ),
    ]
